### ISSUE TITLE
Compilation problems with BandedMatrices

### ISSUE THREAD

**Issue by Datseris** [JuliaDiffEq/DiffEqOperators.jl#188] opened 2019-10-01 12:55 UTC
Seems that I have some compilation issues. I can't compile DiffEqOperators.

```

(v1.2) pkg> add DiffEqOperators
 Resolving package versions...
  Updating `C:\Users\datseris\.julia\environments\v1.2\Project.toml`
  [9fdde737] + DiffEqOperators v4.1.0

Manifest:
  [aae01518] BandedMatrices v0.12.1
```

```

julia> using DiffEqOperators
[ Info: Recompiling stale cache file C:\Users\datseris\.julia\compiled\v1.2\DiffEqOperators\Vx3Cs.ji for DiffEqOperators [9fdde737-9c7f-55bf-ade8-46b3f136cc48]
WARNING: Method definition lmul!(LinearAlgebra.QRPackedQ{#s161, #s160} where #s160<:(BandedMatrices.AbstractBandedMatrix{T} where T) where #s161, Union{AbstractArray{T, 2}, AbstractArray{T, 1}} where T) in module BandedMatrices at C:\Users\datseris\.julia\packages\BandedMatrices\c2JG0\src\banded\bandedqr.jl:160 overwritten at C:\Users\datseris\.julia\packages\BandedMatrices\c2JG0\src\banded\bandedqr.jl:160.
  ** incremental compilation may be fatally broken for this module
**

WARNING: Method definition lmul!(LinearAlgebra.QRPackedQ{#s155, Base.SubArray{T, 2, BandedMatrices.BandedMatrix{T, C, R}, Tuple{I1<:(Base.AbstractUnitRange{T} where T), I2<:(Base.AbstractUnitRange{T} where T)}, t} where t} where #s155, Union{AbstractArray{T, 2}, AbstractArray{T, 1}} where T) where {T, C, R, I1<:(Base.AbstractUnitRange{T} where T), I2<:(Base.AbstractUnitRange{T} where T)} in module BandedMatrices at C:\Users\datseris\.julia\packages\BandedMatrices\c2JG0\src\banded\bandedqr.jl:162 overwritten at C:\Users\datseris\.julia\packages\BandedMatrices\c2JG0\src\banded\bandedqr.jl:162.
  ** incremental compilation may be fatally broken for this module
**

WARNING: Method definition lmul!(LinearAlgebra.Adjoint{#s159, #s158} where #s158<:(LinearAlgebra.QRPackedQ{#s157, #s156} where #s156<:(BandedMatrices.AbstractBandedMatrix{T} where T) where #s157) where #s159, Union{AbstractArray{T, 2}, AbstractArray{T, 1}} where T) in module BandedMatrices at C:\Users\datseris\.julia\packages\BandedMatrices\c2JG0\src\banded\bandedqr.jl:161 overwritten at C:\Users\datseris\.julia\packages\BandedMatrices\c2JG0\src\banded\bandedqr.jl:161.
  ** incremental compilation may be fatally broken for this module
**

WARNING: Method definition lmul!(Li 

...
```

What I cannot know is whether this is an issue specific to me, due to something wrong in my installation or so.

**Comment by ChrisRackauckas** [comment] 2019-10-01 13:29
The precompilation error is due to BandedMatrices according to the error message. You might get more help opening the issue there. Why is BandedMatrices specifically in your manifest? Is it a special version you're using? What happens if you remove it?

**Comment by ChrisRackauckas** [comment] 2019-10-01 13:30
Closing since the issue isn't in this module. I would recommend migrating it with the `using BandedMatrices` MWE to BandedMatrices.jl

**Comment by ChrisRackauckas** [comment] 2019-10-01 13:31
Feel free to continue to discuss here, but of course the real change has to happen in the other repo.

**Closed by ChrisRackauckas** 2019-10-01 13:31 UTC
